POST http://localhost:3000/reports
Content-Type: application/json

{
  "make": "Toyota",
  "model": "Camry",
  "year": 2016,
  "mileage": 50000,
  "price": 15000,
  "lat": 40.7128,
  "lng": 74.0060
}

### Approve a report
PATCH  http://localhost:3000/reports/12
Content-Type: application/json

{
  "approved": true
}

### Get estimated for an existing vehicle
GET  http://localhost:3000/reports?make=Toyota&model=Camry&year=2015&mileage=10000&lat=40.7128&lng=74.0060
Content-Type: application/json
